os:
#  - osx
#  - linux
  - windows

language: node_js

env:
  global:
    - ELECTRON_RUN_AS_NODE=true
#    - PATH="$PATH:$USERPROFILE/.windows-build-tools/python27"

node_js:
  - 12

before_install:
  - node -v
  - npm -v

script:
#  - npm install -g windows-build-tools
#  - npm config set python $USERPROFILE/.windows-build-tools/python27/python.exe
#  - choco install python vcredist140
  - npm install electron@7.1.14
  - node ./node_modules/electron/cli.js --version
