os:
  - osx
  - linux
  - windows

language: node_js

env:
  global:
    - ELECTRON_RUN_AS_NODE=true

node_js:
  - 12

before_install:
  - node -v
  - npm -v
  - npm install -g yarn
  - yarn global bin
  - if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then export PATH=/c/Users/travis/AppData/Local/Yarn/bin:$PATH; fi;

script:
  - yarn global add electron@7.1.14
  - electron --version
