os:
  - osx
  - linux
  - windows

language: node_js

env:
  global:
    - ELECTRON_RUN_AS_NODE=true

node_js:
  - 12

before_install:
  - node -v
  - npm -v

script:
  - npm install -g electron@7.1.14
  - electron --version
